[phases.setup]
nixPkgs = ["nodejs_20", "caddy"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "caddy run --config /app/Caddyfile --adapter caddyfile"
